NixMangaProject/Models/ErrorViewModel.cs
namespace NixMangaProject.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

NixMangaProject/Models/Pager.cs
namespace NixMangaProject.Models
{
    public class Pager
    {
      
        public int TotalItems { get; private set; }
        public int CurrentPage { get; private set; }
        public int PageSize { get; private set; }
        public int TotalPages { get; private set; }
        public int StartPage { get; private set; }
        public int EndPage { get; private set; }
        public Pager() { }
        public Pager(int totalItems, int page, int pageSize=10) {

            int totalPages = (int)Math.Ceiling((decimal)totalItems / (decimal)pageSize);
            int currentPage = page;
            int startPage = currentPage - 5;
            int endPage = currentPage + 4;
            if(startPage <= 0)
            {
                endPage = endPage - (startPage - 1);
                startPage = 1;
            }

            if(endPage > totalPages)
            {
                endPage = totalPages;
                if(endPage > 10)
                {
                    startPage = endPage - 9;
                }
            }

            TotalItems = totalItems;
            CurrentPage = currentPage;
            PageSize = pageSize;
            TotalPages = totalPages;
            StartPage = startPage;
            EndPage = endPage;
        
        }
    }
}

NixMangaProject/Models/ProductImageViewModel.cs
using System.Collections.Generic;
using NixMangaProject.EF.Models;
namespace NixMangaProject.Models
{
    public class ProductImageViewModel
    {
        public IEnumerable<Product> products { get; set; }
        public IEnumerable<Image> images { get; set; }
    }
}

NixMangaProject/Controllers/AddController.cs
using Microsoft.AspNetCore.Mvc;
using NixMangaProject.EF;
using NixMangaProject.EF.Models;

namespace NixMangaProject.Controllers
{
    public class AddController : Controller
    {
        private readonly ManhaShopDbContext _context;

        public AddController(ManhaShopDbContext _context)
        {
            this._context = _context;
        }
        [HttpGet]
        public IActionResult AddPublisher()
        {
            return View();
        }
        [HttpPost]
        public void AddPublisher(string PublisherName, string PublisherDescription, string ContactInfo)
        {
            Publisher pub = new Publisher(PublisherName, PublisherDescription, ContactInfo);
            _context.Publishers.Add(pub);
            _context.SaveChanges();
        }
    }
}

NixMangaProject/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using NixMangaProject.Models;
using System.Diagnostics;

namespace NixMangaProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        
        public IActionResult Index()
        {
            return View();
        }

        //[Route("About")]
        public IActionResult About()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

NixMangaProject/Controllers/KatalogController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NixMangaProject.EF;
using NixMangaProject.EF.Models;
using NixMangaProject.Models;

namespace NixMangaProject.Controllers
{
    public class KatalogController : Controller
    {
        private readonly ManhaShopDbContext _context;

        public KatalogController(ManhaShopDbContext _context)
        {
            this._context = _context;
        }
        
        public async Task<IActionResult> Prosmotr(string sortOrder,string searchString, int pg=1)
        {
            ViewData["Filter"] = sortOrder;
            ViewData["CurrentFilter"] = searchString;
            var product = from p in _context.Products select p;
            switch (sortOrder)
            {
                case "aviable":
                    product = product.OrderByDescending(s => s.ProductAviable);
                    break;
                case "downTohight":
                    product = product.OrderBy(s => s.ProductCost);
                    break;
                case "HightToDown":
                    product = product.OrderByDescending(s => s.ProductCost);
                    break;
                default:
                    product = product.OrderBy(s => s.ProductName);
                    break;
            }
            if (!String.IsNullOrEmpty(searchString))
            {
                product = product.Where(s => s.ProductName.Contains(searchString));
            }
            List<Product> products = await product.AsNoTracking().ToListAsync();
            const int pageSize = 3;
            if (pg < 1) { pg = 1; }
            int rescCount = products.Count();
            var pager = new Pager(rescCount, pg, pageSize);
            int recSkip = (pg - 1) * pageSize;
            var data = products.Skip(recSkip).Take(pager.PageSize).ToList();
            var img = _context.Images.ToList();
            ProductImageViewModel PrIg = new ProductImageViewModel { products = data , images = img};
            this.ViewBag.Pager = pager;
            return View(PrIg);
        }
    }
}

NixMangaProject/Views/Add/AddPublisher.cshtml
@using NixMangaProject.EF.Models;
@model Publisher;
@{
    ViewData["Title"] = "AddPublisher";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Добавить издателя</title>
</head>
<body>

<div class="Main__container">
          <form asp-action="AddPublisher" asp-controller="Add" method="post">
          <div class="container"> 
                <div class="Help"><p class="Help_text">Для добавления издателя заполните поля ниже</p></div>    
                <div class="row">
                  <div class="col-sm-6">
                    <div class="Child_Name"><label for="InputName" class="label__Name">Имя издателя</label></div>
                  </div>
                  <div class="col-sm-6">
                    <div class="InputChild_Name">
                      <input type="text" asp-for="PublisherName" class="form-control" id="InputName" aria-describedby="NameHelp" placeholder="Введите минимум 3 символа">
                    </div>  
                  </div>
                </div>
                <div class="row">
                  <div class="col-sm-6">
                    <div class="Child_Name"><label for="InputDescription" class="label__Description">Описание издателя</label> </div>
                  </div>
                  <div class="col-sm-6">
                    <div class="InputChild_Name">
                      <textarea class="form-control" asp-for="PublisherDescription" id="FormControlTextarea__Description" rows="3" placeholder="Введите минимум 3 символа"></textarea>
                    </div> 
                  </div>
                </div>
                 <div class="row">
                  <div class="col-sm-6">
                    <div class="Child_Name"><label for="InputName" class="label__Name">Контакты издателя</label></div>
                  </div>
                  <div class="col-sm-6">
                    <div class="InputChild_Name">
                      <input type="text"  asp-for="ContactInfo" class="form-control" id="InputName" aria-describedby="NameHelp" placeholder="Введите минимум 3 символа">
                    </div>  
                  </div>
                </div>
                <div class="row">
                  <div class="col-sm-6">
                    <div class="Child_BTN"><button type="submit" class="btn btn-success btn-lg" value="Добавить">Добавить</button></div>
                  </div>
                  <div class="col-sm-6">
                    <div class="Child_BTN"><button type="button" class="btn btn-warning btn-lg" onclick="Clear();">Очистить</button></div>
                  </div>
                </div>
          </div>   
          </form>
</div>
</body>
</html>

NixMangaProject/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>О нас</title>
</head>
<body>
    <div class="Main__container">
        <div class="container">
            <div class="row">
              <div class="col-s-12 col-md-6" id="Text">
                  <div class="AboutText">Всем привет! Меня зовут Лёша, я студент 2 курса програмной инженерии в ХНУРЭ, моё фото показано на слайдере. То что вы видите - моя первая попытка сделать что-то серьезное и масштабное. Тема манги была выбрана из-за моей большой любви к ней. Если эта работа будет выложена в общий доступ то я крайне благодарен за посещение данного сайта</div>
                  <div class="AboutText">Касательно вопросов или предложений можете писать на эту почту - kosinskiy02@ukr.net </div>
                  </div>
              <div class="col-s-1 col-md-6 Karusel" id="Photo">
                    <!-- Карусель -->
                    <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
                        <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img src="/image/me1.jpg" class="d-block w-100" alt="...">
                        </div>
                        <div class="carousel-item">
                            <img src="/image/me2.jpg" class="d-block w-100" alt="...">
                        </div>
                        <div class="carousel-item">
                            <img src="/image/me3.jpg" class="d-block w-100" alt="...">
                        </div>
                        </div>
                        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls"  data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Предыдущий</span>
                        </button>
                        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls"  data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Следующий</span>
                        </button>
                    </div>
              </div>
            </div>
        </div>
    </div>
</body>
</html>

NixMangaProject/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Главная</title>
</head>
<body>
    <div class ="proverka67"></div>
    <div class="main">
        <div class="main__container">
            <div class="main__inner">
                <div class="main__welcome">
                    <h1>Добро пожаловать в мир манги, мы ждали тебя!</h1>
                    <p class=""> В каталоге нашего магазина вы найдете культовые произведения в жанре манга для взрослых и детей, рассказывающие интересные и захватывающие истории. В хороших руках манга может стать отличным способом познания окружающего мира, так как идеально передает мироощущение за счет хитрых графических приемов.
                    </p>
                    <input type="button" value=" Заказать мангу" class = "main__button" >
                </div>
            </div>
        </div>
    </div>

    <div class="advantages">
        <div class="advantages__container">
            <div class="advantages__inner"> 
              <div class="advantages__grid-header"> Почему именно мы?</div>
              <div class="advantages__grid-pictures1"> <img src="/Image/adbantages_1.png" alt=""></div>
              <div class="advantages__grid-text1"> <p class="advText">Отличные менеджеры, которые готовы всегда помочь с выбором товара</p></div>
              <div class="advantages__grid-pictures2"><img src="/Image/060-coin-dollar.png" alt=""></div>
              <div class="advantages__grid-text2"> <p class="advText">Самые низкие цены среди всех магазинов</p></div>
              <div class="advantages__grid-pictures3"> <img src="/Image/084-calendar.png" alt=""></div>
              <div class="advantages__grid-text3"> <p class="advText">Быстрая доставка. Заказы всегда приходят в указаный срок</p></div>
            </div>
        </div>  
    </div>
</body>
</html>

NixMangaProject/Views/Katalog/Prosmotr.cshtml
@using NixMangaProject.EF.Models;
@using NixMangaProject.Models;
@model ProductImageViewModel;
@{
    ViewData["Title"] = "Katalog";
    Pager pager = new Pager();
    int pageNo = 0;
    if (ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
        pageNo = pager.CurrentPage;
    }
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Каталог</title>
</head>
<body>
    <div class="Main__container">
       <form asp-action="Prosmotr" method="get">
            <div class="container" id="SearchContainer">
                    <p class="searchText">Введите название товара: </p>
                    <div class="SearchOgran form-group"><input type="text" class="form-control" name="SearchString" value="@ViewData["CurrentFilter"]" /></div> 
                    <button type="submit" class="btn btn-info btn-lg">Поиск</button>
                    <a asp-action="Prosmotr" class="btn btn-link btn-lg">Вернуться к списку</a>
            </div>
       </form>
         <div class = "container">
              <div class="row" id="searchFiltercontainer">
               <div class="row">
                     <div class="col">
                         <a class="search__nav-link" asp-controller="Katalog" asp-action="Prosmotr" asp-route-sortOrder = "aviable" >В наличии</a>
                        </div>
                       <div class="col">
                        <a class="search__nav-link" asp-controller="Katalog" asp-action="Prosmotr"  asp-route-sortOrder = "downTohight">От дешевых</a>
                         </div>
                      <div class="col">
                        <a class="search__nav-link" asp-controller="Katalog" asp-action="Prosmotr"  asp-route-sortOrder = "HightToDown">От дорогих</a>
                      </div>
                     <div class="col">
                        <a class="search__nav-link" asp-controller="Katalog" asp-action="Prosmotr">Убрать фильтры</a>
                     </div>
                </div>
              </div>
        </div>
      
        @foreach(var item in Model.products){
            string s="";
            double a = Convert.ToDouble(@item.ProductCost);
            @foreach(var it in Model.images)
            {
                if (item.ProductId == it.ProductId){ s = it.ImgSource; }
            }
            <div class="container"  id="heading">
                    <div class="row">
                    <div class="col-xl-2 col-lg-2 col-md-12 col-sm-12"> <div class="body-catalog__item1-icon" ><img src="@s" alt="" id="heading1"></div></div>
                    <div class="col-xl-10 col-lg-10 col-md-12 col-sm-12">
                        <label for="exampleInputEmail1" class="form-label body-catalog__item1-title"><div class="textcenter">@item.ProductName</div></label>
                        <label for="exampleInputEmail1" class="form-label body-catalog__item1-title"><div class="textcenter"> - @a Гривен</div></label>
                      <div class="row"> @*@s*@
                        <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12">
                            <label for="exampleInputEmail1" class="form-label"><div class="textcenter"><div class="descriptionInform">@item.ProductDescription</div></div></label>
                        </div>
                        <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12">
                            <div class="row"><button type="submit" class="btn btn-success" id="textbuttonProsmort">Купить</button></div>
                            <div class="row"><button type="submit" class="btn btn-warning" id="textbuttonProsmort">Подробнее</button></div>  
                        </div>
                      </div>
                    </div>
                </div>
            </div>
        }
        <div class = "container">
            @if(pager.TotalPages > 0)
            {
                <ul class="pagination justify-content-end">

                    @if(pager.CurrentPage > 1)
                    {
                        <li class="page-item">
                             <a class="page-link" asp-controller="Katalog" asp-action="Prosmotr"  asp-route-searchString ="@ViewData["CurrentFilter"]" asp-route-pg= "1">Первая</a>
                        </li>
                        <li>
                             <a class="page-link" asp-controller="Katalog" asp-action="Prosmotr"  asp-route-searchString ="@ViewData["CurrentFilter"]" asp-route-pg= "@(pager.CurrentPage - 1)">Предыдущая</a>
                        </li>
                    }

                    @for(var pge=pager.StartPage; pge <= pager.EndPage; pge++)
                    {
                        <li class = "page-item @(pge == pager.CurrentPage ? "active" : "")">
                            <a class="page-link" asp-controller="Katalog" asp-action="Prosmotr" asp-route-sortOrder ="@ViewData["Filter"]" asp-route-searchString ="@ViewData["CurrentFilter"]" asp-route-pg= "@pge">@pge</a>
                        </li>
                    }

                    @if( pager.CurrentPage < pager.TotalPages){

                        <li class="page-item">
                             <a class="page-link" asp-controller="Katalog" asp-action="Prosmotr"  asp-route-searchString ="@ViewData["CurrentFilter"]" asp-route-pg= "@(pager.CurrentPage + 1)">Следующая</a>
                        </li>
                        <li>
                             <a class="page-link" asp-controller="Katalog" asp-action="Prosmotr"  asp-route-searchString ="@ViewData["CurrentFilter"]" asp-route-pg= "@(pager.TotalPages)">Последняя</a>
                        </li>
                    }
                </ul>
            }
        </div>
    </div>
</body>
</html>

NixMangaProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="/css/StyleSheet.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Merriweather:ital@1&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Balsamiq+Sans:ital@1&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Merriweather:ital@1&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Philosopher:wght@700&family=Roboto+Slab:wght@300&display=swap" rel="stylesheet">
</head>
<body>
    <div class="page">
       <header class="header">
        <div class="header__container">
          <div class="header__inner">
              <div class="header__logo">BuyManga</div>
              <nav class="header__nav">
                 <div class="header__hamburger-menu">
                     <input id="header__menu-toggle" type="checkbox">
                     <label class="header__menu-btn" for="header__menu-toggle">
                       <span></span>
                     </label>
                 
                     <ul class="header__menu-box">
                             <li><a class="header__menu-item" href="~/Home/Index">Главная</a></li>
                             <li><a class="header__menu-item" href="~/Katalog/Prosmotr">Каталог</a></li>
                             <li><a class="header__menu-item" href="">Корзина</a></li>
                             <li><a class="header__menu-item" href="~/Home/About">О нас</a></li>
                             <li><a class="header__menu-item" href="#">Вход</a></li>
                     </ul>
                   </div>
                  <a class="header__nav-link" href="~/Home/Index">Главная</a>
                  <a class="header__nav-link" href="~/Katalog/Prosmotr">Каталог</a>
                  <a class="header__nav-link" href="~/Add/AddPublisher">Корзина</a>
                  <a class="header__nav-link" href="~/Home/About">О нас</a>
                  <a class="header__nav-link" href="#">Вход</a>
              </nav>
          </div>
         </div>
       </header>
            @RenderBody()
        <footer class="footer">
         <div class="footer__container">
            <div class="footer__inner">
                <div class="footer__logosocial"> <div class="footer__insta"><a href="https://www.instagram.com/lonesome_jaba/"><img src="/image/403-instagram.png" alt=""></a></div><div class="footer__telega"><a href=""><img src="/image/406-telegram.png" alt=""></a></div><div class="footer__youtube"><a href="https://www.youtube.com/"><img src="/image/414-youtube.png" alt=""></a></div></div>
                <div class="footer__connect">Связаться с нами</div>
                <div class="footer__number"> +380985742522</div>
                <div class="footer__reserved"> Все права защищены</div>
            </div>
         </div>
        </footer>
    </div>
</body>
</html>